site_name: My Docs
site_url: !ENV
repo_url: https://github.com/TODO/TODO
repo_name: TODO/TODO
edit_uri:
copyright:

nav:
  - ''
  - Beginner Tutorials
  - How-to Guides
  - Reference
  - Explanations

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate

plugins: [ search ]

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link:
      name:
    - icon: fontawesome/brands/discord
      link:
      name: