site_name: DisQuark Docs
site_url: https://docs.disquark.io

repo_url: https://github.com/disquark/disquark
repo_name: disquark/disquark

docs_dir: src/main/markdown
edit_uri: edit/main/docs/src/main/markdown

copyright:

nav:
  - 'index.md'
  - Beginner Tutorials: '/tutorials'
  - How-to Guides: '/guides'
  - Reference: 'https://javadoc.io/doc/io.disquark/disquark-rest/latest/index.html'

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - macros:
      include_dir: macros
      include_yaml: mkdocs-macros.yml
      on_error_fail: true

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/disquark
    - icon: fontawesome/brands/discord
      link: https://github.com/disquark