site_name: DisQuark
site_url: https://docs.disquark.io

repo_url: https://github.com/disquark/disquark
repo_name: disquark/disquark

docs_dir: src/main/markdown
edit_uri: edit/main/docs/src/main/markdown

copyright:

nav:
  - Home: index.md
  - Beginner Tutorials:
      - tutorials/getting-started.md
      - tutorials/smallrye-mutiny.md
      - tutorials/role-selector-bot.md
  - How-to Guides:
      - guides/logging.md
      - guides/interactions.md
  - Reference: https://javadoc.io/doc/io.disquark/disquark-rest/latest/index.html

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate

plugins: [ search ]

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike
  versions:
    disquark: 999-SNAPSHOT
    bouncycastle: 1.70
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/disquark
    - icon: fontawesome/brands/discord
      link: https://github.com/disquark