site_name: DisQuark Docs
site_url: https://docs.disquark.io

repo_url: https://github.com/disquark/disquark
repo_name: disquark/disquark

docs_dir: src
edit_uri: edit/main/docs/src

copyright: >-
  Site content licensed under the <a href="https://creativecommons.org/licenses/by/4.0/">CC Attribution 4.0 International License</a>.

nav:
  - Home: index.md
  - Beginner Tutorials:
      - tutorials/getting-started.md
      - tutorials/smallrye-mutiny.md
      - tutorials/role-selector-bot.md
  - How-to Guides:
      - guides/logging.md
  - Reference: https://javadoc.io/doc/io.disquark/disquark-rest/latest/index.html

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark theme
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light theme
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate

plugins: [ search ]

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  version:
    provider: mike
  versions:
    disquark: ${project.version}
    bouncycastle: ${bouncycastle.version}
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/disquark